# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twdcxtP6eliG9mKKHKmEtpapiuibSksj
"""

##Loading the  Dataset

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("Heart_Failure_Details.csv")

#print First 5 Rows

print(df.head())

#Checking Missing Values

print("\nMissing Values:\n", df.isnull().sum())

#Checking for Duplicate Values

print("\nDuplicate Values:", df.duplicated().sum())

#charts

#Histogram: Age Distribution of Patients

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 5))
sns.histplot(df["age"], bins=20, kde=True, color="blue")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.title("Age Distribution of Patients")
plt.show()

# Pie Chart: Death vs. Survived Patients

plt.figure(figsize=(6, 6))
df["death"].value_counts().plot.pie(autopct="%1.1f%%", colors=["green", "red"])
plt.title("Death vs. Survived Patients")
plt.ylabel("")
plt.show()

#Bar Chart: Comparison of Heart Failure in Males vs. Females

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x="sex", hue="death", palette=["green", "red"])
plt.xlabel("Sex (0 = Female, 1 = Male)")
plt.ylabel("Count")
plt.title("Heart Failure Cases: Male vs. Female")
plt.show()

# Box Plot: Serum Creatinine Levels vs. Death

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="death", y="serum creatinine", palette=["green", "red"])
plt.xlabel("Death (0 = No, 1 = Yes)")
plt.ylabel("Serum Creatinine Levels")
plt.title("Serum Creatinine Levels in Survived vs. Deceased Patients")
plt.show()

#Heatmap: Correlation Between Features

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

#Line Chart: Ejection Fraction vs. Age

plt.figure(figsize=(8, 5))
sns.lineplot(data=df, x="age", y="ejection fraction", marker="o", color="blue")
plt.xlabel("Age")
plt.ylabel("Ejection Fraction")
plt.title("Ejection Fraction vs. Age")
plt.show()

# Scatter Plot: Serum Sodium vs. Age

plt.figure(figsize=(8, 5))
sns.scatterplot(data=df, x="age", y="serum sodium", hue="death", palette=["green", "red"])
plt.xlabel("Age")
plt.ylabel("Serum Sodium")
plt.title("Serum Sodium Levels vs. Age")
plt.show()

#Bubble Chart: Platelets vs. Serum Creatinine (Size = Age)

plt.figure(figsize=(8, 5))
plt.scatter(df["platelets"], df["serum creatinine"], s=df["age"]*2, alpha=0.5, c=df["death"], cmap="coolwarm")
plt.xlabel("Platelets")
plt.ylabel("Serum Creatinine")
plt.title("Bubble Chart: Platelets vs. Serum Creatinine")
plt.colorbar(label="Death (0 = No, 1 = Yes)")
plt.show()

# Area Chart: Creatinine Phosphokinase Levels Over Age

plt.figure(figsize=(8, 5))
sns.kdeplot(data=df, x="age", y="creatinine phosphokinase", fill=True, cmap="Blues")
plt.xlabel("Age")
plt.ylabel("Creatinine Phosphokinase")
plt.title("Creatinine Phosphokinase Levels Over Age")
plt.show()

